# Generated by Django 4.2 on 2024-08-26 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("med", "0010_remove_services_doctor_alter_appointment_doctor_and_more"),
        ("users", "0003_user_is_doctor"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="services",
            field=models.ManyToManyField(
                related_name="services", to="med.services", verbose_name="услуги"
            ),
        ),
    ]
