# Generated by Django 4.2 on 2024-08-26 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("med", "0010_remove_services_doctor_alter_appointment_doctor_and_more"),
        ("users", "0004_user_services"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="services",
            field=models.ManyToManyField(
                blank=True,
                null=True,
                related_name="services",
                to="med.services",
                verbose_name="услуги",
            ),
        ),
    ]
