# Generated by Django 4.2 on 2024-08-27 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("med", "0011_remove_services_appointments"),
        ("users", "0008_alter_user_services"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="services",
            field=models.ManyToManyField(
                blank=True,
                null=True,
                related_name="services",
                to="med.services",
                verbose_name="услуги",
            ),
        ),
    ]
