# Generated by Django 4.2 on 2024-08-21 22:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Doctor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=30, verbose_name="Имя")),
                ("last_name", models.CharField(max_length=30, verbose_name="Фамилия")),
                (
                    "photo",
                    models.ImageField(
                        blank=True, null=True, upload_to="person/", verbose_name="Фото"
                    ),
                ),
            ],
            options={
                "verbose_name": "доктор",
                "verbose_name_plural": "доктора",
            },
        ),
        migrations.CreateModel(
            name="Feedback",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="имя")),
                ("email", models.EmailField(max_length=254, verbose_name="e-mail")),
                ("text", models.TextField(verbose_name="текст")),
                ("date", models.DateTimeField(verbose_name="дата и время отзыва")),
            ],
            options={
                "verbose_name": "отзыв",
                "verbose_name_plural": "отзывы",
            },
        ),
        migrations.CreateModel(
            name="Services",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=100, verbose_name="наименование"),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="описание"),
                ),
                ("price", models.PositiveIntegerField(verbose_name="стоимость")),
                (
                    "doctor",
                    models.ManyToManyField(related_name="доктор", to="med.doctor"),
                ),
            ],
            options={
                "verbose_name": "услуга",
                "verbose_name_plural": "услуги",
            },
        ),
        migrations.AddField(
            model_name="doctor",
            name="speciality",
            field=models.ManyToManyField(
                related_name="services", to="med.services", verbose_name="Услуги"
            ),
        ),
        migrations.CreateModel(
            name="Appointment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateTimeField(verbose_name="дата и время приема")),
                (
                    "diagnostic",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="записи",
                        to="med.services",
                        verbose_name="диагностика",
                    ),
                ),
                (
                    "doctor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="записи",
                        to="med.doctor",
                        verbose_name="врач",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="записи",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="пациент",
                    ),
                ),
            ],
            options={
                "verbose_name": "запись на диагностику",
                "verbose_name_plural": "записи на диагностику",
            },
        ),
    ]
