# Generated by Django 4.2 on 2024-08-21 23:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("med", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="doctor",
            old_name="speciality",
            new_name="services",
        ),
    ]
