# Generated by Django 4.2 on 2024-08-21 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("med", "0002_rename_speciality_doctor_services"),
    ]

    operations = [
        migrations.AlterField(
            model_name="doctor",
            name="services",
            field=models.ManyToManyField(
                blank=True,
                null=True,
                related_name="services",
                to="med.services",
                verbose_name="Услуги",
            ),
        ),
    ]
