# Generated by Django 4.2 on 2024-08-25 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("med", "0006_delete_feedback"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="doctor",
            name="services",
        ),
        migrations.AddField(
            model_name="services",
            name="doctor",
            field=models.ManyToManyField(to="med.doctor", verbose_name="доктор"),
        ),
    ]
