# Generated by Django 4.2 on 2024-08-25 23:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("med", "0007_remove_doctor_services_services_doctor"),
    ]

    operations = [
        migrations.AddField(
            model_name="services",
            name="appointments",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="appointments",
                to="med.appointment",
                verbose_name="запись",
            ),
        ),
    ]
