# Generated by Django 4.2 on 2024-08-26 20:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("med", "0009_alter_appointment_services"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="services",
            name="doctor",
        ),
        migrations.AlterField(
            model_name="appointment",
            name="doctor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user",
                to=settings.AUTH_USER_MODEL,
                verbose_name="врач",
            ),
        ),
        migrations.DeleteModel(
            name="Doctor",
        ),
    ]
