# Generated by Django 4.2 on 2024-08-27 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("med", "0010_remove_services_doctor_alter_appointment_doctor_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="services",
            name="appointments",
        ),
    ]
